---
# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# ---------------------------
#   Composer configuration
# ---------------------------

# .. envvar:: composer__bin_dir
#
# Local system bin directory.
composer__bin_dir: '{{ ansible_local.root.bin
                         if (ansible_local|d() and ansible_local.root|d() and
                             ansible_local.root.bin|d())
                         else "/usr/local/bin" }}'
