---

- name: Download Composer installer
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: '/tmp/composer-installer.php'
    mode: 0755

- name: Run Composer installer
  command: 'php composer-installer.php'
  args:
    chdir: '/tmp'
    creates: '/tmp/composer.phar'

- name: Move composer to local system bin directory
  command: 'mv /tmp/composer.phar {{ composer__bin_dir }}/composer'
  args:
    creates: '{{ composer__bin_dir }}/composer'
